### PR TITLE
Refactor getData

### PR DESCRIPTION
**Pull request by zaaj**
Adam Johnson from FRC Team 95, The Grasshoppers here.  We've been using a fork of your ScoutingPASS from last year.  Our head coach suggested we collaborate with your team more closely than just making a fork on GitHub.
We had stripped out several features and simplified the data format encoded in the QR Code, so some of the code cleanup changes I made last year wouldn't be directly usable for your team.  I finally had some spare time, so I've re-forked your code, and re-applied just the code-simplification type changes, slightly differently since this time I figured I'd try my hand at creating a Pull Request (first time).
I even got to figure out how to re-base my branch due to updates you've posted yesterday while I was working on my forked branch ;)

Here's the pull request for your review.  Only one user-visible change:  I added field titles to the short field names listed in the missing-required-fields pop-up message - 
"s: Scouter Initials"
"m: Match #"
Seemed friendlier that 
"s m"

### CODE REVIEW

**Comment by zaaj** [comment]
I've just pulled in fuddster's most recent 3 commits into this pull request to keep it up-to-date with upstream changes

**Comment by fuddster** [comment]
Thank you for your changes!   I've briefly reviewed them and they look good.  I'll review them in more detail and incorporate them when things slow down.   We're going overtime right now to prepare for our first competition.

**Comment by zaaj** [comment]
Just another merge commit to keep this pull request up to date with upstream

**Comment by zaaj** [comment]
I Checked The Blue Alliance to check which event you might be referring to in your last comment, and Finals were being livestreamed as I checked - watched your first round finals match - it would appear that overtime paid off - a win even with one alliance member hung up in the scoring area - well done!

**Comment by zaaj** [comment]
Merged upstream/Main branch changes from last two weeks into my pull request branch again

**Comment by zaaj** [comment]
Finally circled back to refresh this pull request now that we're in the off-season

**Comment by zaaj** [comment]
I noticed that getData took a true/false parameter, but that in all three places it was called, True was the parameter given.  Our team has been using tab-separated values as the output format, so we can just put the cursor in Column A on the first blank row of our data collection spreadsheet, and use a USB 2D barcode scanner to read the data directly into the sheet - no need for any parsing scripts.

I changed the meaning of the true/false to expect "kvs" for key=value; (key, value, semicolon) the format your team is using with the parsing script in Excel, but it now also accepts "tsv" for the tab separated values. 
The configure() function has a stanza to read this into a variable, and the Configure.md now describes the option as well.

I've seen some Issues opened asking for help with the parsing script, so maybe this pull request can address those by side-stepping the need for parsing for teams that are not using Excel (on a Mac, or Linux, for example)

**Review by fuddster — APPROVED** [review]
The changes look great.

Thank you for this!

**Pull request merged**
